from __future__ import annotations

import contextlib
from typing import Generator
from typing import Protocol
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import curses


class StatusProto(Protocol):
    def writeln(self, header: str, body: str | None = None) -> None: ...
    def error(self, header: str, body: str | None = None) -> None: ...
    def success(self, header: str, body: str | None = None) -> None: ...
    def attention(self, header: str, body: str | None = None) -> None: ...
    def clear(self) -> None: ...


class ScreenBufferProto(Protocol):
    win: curses.window
    @contextlib.contextmanager
    def extra_margin(self, n: int) -> Generator[None]: ...
    def draw(self) -> None: ...
    def resize(self) -> None: ...
